name: Identifying Secrets in the Repository with git-secrets

on:
  push:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install git-secrets
      run: |
        git clone https://github.com/awslabs/git-secrets.git
        cd git-secrets
        sudo make install
    
    - name: Run scan with git-secrets
      run: |
        export URL=https://gist.githubusercontent.com/ayushpriya10/cffb907a9fb0f3546d623c023c2bd4ce/raw/867a98cbf8dd0dfc0bf188d34f7b4613804e10b9/git-secrets-signatures
        curl $URL > signatures
        git secrets --add-provider -- cat signatures
        git secrets --scan 2>scan-output || true
        echo "file_exists=`ls | grep scan-output`" >> GITHUB_ENV
        ls
        
    - name: Upload Scan Report as Artifact to GitHub
      if: ${{ env.file_exists == 'scan-output' }}
      uses: actions/upload-artifact@v2
      with:
        name: Git-Secrets-Report
        path: scan-output
